/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'mcp-servers': McpServer;
    'ai-tools': AiTool;
    categories: Category;
    media: Media;
    users: User;
    'credit-transactions': CreditTransaction;
    'redeem-batches': RedeemBatch;
    'redeem-codes': RedeemCode;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'mcp-servers': McpServersSelect<false> | McpServersSelect<true>;
    'ai-tools': AiToolsSelect<false> | AiToolsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'credit-transactions': CreditTransactionsSelect<false> | CreditTransactionsSelect<true>;
    'redeem-batches': RedeemBatchesSelect<false> | RedeemBatchesSelect<true>;
    'redeem-codes': RedeemCodesSelect<false> | RedeemCodesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mcp-servers".
 */
export interface McpServer {
  id: number;
  name: string;
  /**
   * 显示在卡片上，建议 50 字以内
   */
  summary: string;
  /**
   * 不上传则自动用名称首字生成图标
   */
  logo?: (number | null) | Media;
  category?: (number | null) | Category;
  tags?: string[] | null;
  /**
   * 支持 Markdown，可以直接粘贴 README
   */
  description?: string | null;
  /**
   * 展示在详情页，让用户知道接入后能做什么
   */
  tools?:
    | {
        name: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 用户客户端连接的地址，例如 https://mcp.example.com/weather/mcp
   */
  endpoint: string;
  transport: 'http' | 'sse';
  /**
   * 填 0 表示免费
   */
  creditsPerCall: number;
  version?: string | null;
  /**
   * 用于网址和客户端配置，只能用小写字母、数字和横线，例如 weather
   */
  slug: string;
  status: 'published' | 'hidden';
  /**
   * 推荐的会排在前面并带标记
   */
  featured?: boolean | null;
  /**
   * 数字越小越靠前
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * 用于网址筛选，例如 productivity
   */
  slug: string;
  kind: 'mcp' | 'tool';
  /**
   * 数字越小越靠前
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-tools".
 */
export interface AiTool {
  id: number;
  name: string;
  /**
   * 显示在卡片上，建议 50 字以内
   */
  summary: string;
  /**
   * 不上传则自动用名称首字生成图标
   */
  logo?: (number | null) | Media;
  category?: (number | null) | Category;
  tags?: string[] | null;
  /**
   * 支持 Markdown，可以直接粘贴 README
   */
  description?: string | null;
  /**
   * 点击“开始使用”后打开的网址，例如 https://music.example.com
   */
  url: string;
  /**
   * 填 0 表示免费
   */
  creditsPerUse: number;
  badge?: ('new' | 'hot' | 'beta') | null;
  /**
   * 用于网址和客户端配置，只能用小写字母、数字和横线，例如 weather
   */
  slug: string;
  status: 'published' | 'hidden';
  /**
   * 推荐的会排在前面并带标记
   */
  featured?: boolean | null;
  /**
   * 数字越小越靠前
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  nickname?: string | null;
  role: 'admin' | 'user';
  /**
   * 要加减积分，请到“积分流水”新建一条调整记录
   */
  credits: number;
  /**
   * 用户在 MCP 客户端和 AI 工具中使用的密钥
   */
  apiKey?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * 想给用户加减积分，点标题旁的“创建新条目”，填用户和数量即可（负数为扣减）。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credit-transactions".
 */
export interface CreditTransaction {
  id: number;
  user: number | User;
  /**
   * 正数为增加，负数为扣减
   */
  amount: number;
  /**
   * 用户在积分记录里能看到，比如“客服补偿”
   */
  note?: string | null;
  type?: ('signup' | 'redeem' | 'consume' | 'refund' | 'admin') | null;
  balanceAfter?: number | null;
  /**
   * 消费时记录，如 mcp/pdf-parser
   */
  product?: string | null;
  redeemCode?: (number | null) | RedeemCode;
  operator?: (number | null) | User;
  key?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redeem-codes".
 */
export interface RedeemCode {
  id: number;
  code: string;
  batch: number | RedeemBatch;
  credits: number;
  status: 'unused' | 'used' | 'disabled';
  usedBy?: (number | null) | User;
  usedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 新建批次会按数量生成卡密，保存后在批次详情里导出 txt，上传到发卡平台销售。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redeem-batches".
 */
export interface RedeemBatch {
  id: number;
  /**
   * 自己看的，比如“淘宝 100 积分 第 1 批”
   */
  name: string;
  /**
   * 每张卡密能兑换的积分，生成后不能改
   */
  credits: number;
  /**
   * 一次最多 5000 张，生成后不能改
   */
  quantity: number;
  /**
   * 不填则永久有效；过期后未兑换的卡密不能再兑换
   */
  expiresAt?: string | null;
  /**
   * 卡密泄露或下架时勾选，本批未兑换的卡密全部不能再兑换
   */
  disabled?: boolean | null;
  note?: string | null;
  usedCount?: number | null;
  unusedCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'mcp-servers';
        value: number | McpServer;
      } | null)
    | ({
        relationTo: 'ai-tools';
        value: number | AiTool;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'credit-transactions';
        value: number | CreditTransaction;
      } | null)
    | ({
        relationTo: 'redeem-batches';
        value: number | RedeemBatch;
      } | null)
    | ({
        relationTo: 'redeem-codes';
        value: number | RedeemCode;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mcp-servers_select".
 */
export interface McpServersSelect<T extends boolean = true> {
  name?: T;
  summary?: T;
  logo?: T;
  category?: T;
  tags?: T;
  description?: T;
  tools?:
    | T
    | {
        name?: T;
        description?: T;
        id?: T;
      };
  endpoint?: T;
  transport?: T;
  creditsPerCall?: T;
  version?: T;
  slug?: T;
  status?: T;
  featured?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-tools_select".
 */
export interface AiToolsSelect<T extends boolean = true> {
  name?: T;
  summary?: T;
  logo?: T;
  category?: T;
  tags?: T;
  description?: T;
  url?: T;
  creditsPerUse?: T;
  badge?: T;
  slug?: T;
  status?: T;
  featured?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  kind?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  nickname?: T;
  role?: T;
  credits?: T;
  apiKey?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credit-transactions_select".
 */
export interface CreditTransactionsSelect<T extends boolean = true> {
  user?: T;
  amount?: T;
  note?: T;
  type?: T;
  balanceAfter?: T;
  product?: T;
  redeemCode?: T;
  operator?: T;
  key?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redeem-batches_select".
 */
export interface RedeemBatchesSelect<T extends boolean = true> {
  name?: T;
  credits?: T;
  quantity?: T;
  expiresAt?: T;
  disabled?: T;
  note?: T;
  usedCount?: T;
  unusedCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redeem-codes_select".
 */
export interface RedeemCodesSelect<T extends boolean = true> {
  code?: T;
  batch?: T;
  credits?: T;
  status?: T;
  usedBy?: T;
  usedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  /**
   * 显示在页脚和搜索引擎结果里
   */
  tagline?: string | null;
  logo?: (number | null) | Media;
  /**
   * 国内网站需在页脚展示，例如 京ICP备12345678号
   */
  icp?: string | null;
  /**
   * 例如客服微信号或邮箱
   */
  contact?: string | null;
  mcpHeroLabel?: string | null;
  mcpHeroTitle?: string | null;
  mcpHeroHighlight?: string | null;
  mcpHeroSubtitle?: string | null;
  toolsHeroTitle?: string | null;
  toolsHeroHighlight?: string | null;
  toolsHeroSubtitle?: string | null;
  signupBonus?: number | null;
  /**
   * 你的发卡平台或店铺链接，用户中心会显示“购买卡密”按钮
   */
  buyCodesUrl?: string | null;
  redeemNote?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  logo?: T;
  icp?: T;
  contact?: T;
  mcpHeroLabel?: T;
  mcpHeroTitle?: T;
  mcpHeroHighlight?: T;
  mcpHeroSubtitle?: T;
  toolsHeroTitle?: T;
  toolsHeroHighlight?: T;
  toolsHeroSubtitle?: T;
  signupBonus?: T;
  buyCodesUrl?: T;
  redeemNote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}